// export const metadata = {
//   title: 'Digital Wall',
//   description: 'Generated by Heet Dedakiya',
// }

export default function RootLayout({ children }) {
  // console.log("hello");
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  )
}
